name: 🐞 [BUG] -  
description: 
labels: ['Needs: Triage :mag:', 'type:bug']

body:
- type: input
  id: sample
  validations:
    required: true
  attributes:
    label: Sample
    description: |
        Which sample are you having troubles with?
        
        Use the sample name or URL. We don't want to be spend all this time diagnosing issues about the wrong sample, do we?

- type: input
  id: authors
  validations:
    required: true
  attributes:
    label: Author(s)
    description: |
        
        
        **NOTE:** Don't @mention the repo maintainers, they already get notified.

- type: markdown
  attributes:
    value: |
      
      
      **Please add your SharePoint link for attachments** 

- type: textarea
  id: what-happened
  attributes:
    label: Issue Description
    description: 
    placeholder: Tell us what you see!
  validations:
    required: true

- type: textarea
  id: steps
  attributes:
    label: Steps to reproduce
    description: How do you reproduce this? Please provide as much step-by-step detail as possible.
    value: |
      1.
      2.
      3.
  validations:
    required: true

- type: textarea
  id: expected
  attributes:
    label: Expected behavior
    description: What did you expect to happen when the reproduce steps are followed?
    placeholder: Tell us what you expected to see!
  validations:
    required: true
