name: 🐞 Bug Report
description: Bug Reporting
title: "🐞[BUG] :  "
labels:  [bug]
projects: ["YogendraBG/2"]

body:
- type: textarea
  id: steps
  attributes:
    label: Issue Description 
    description: How do you reproduce this? Please provide as much step-by-step detail as possible.
    value: |
      1.
      2.
      3.

     
        ✅Expected Behaviour:
        -
        
        ❌Actual   Behaviour:
        -

        📸Evidences Screenshots/Video/pbix:
        -
        
  validations:
    required: true
    
      
      
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
 
- type: checkboxes
  id: terms
  attributes:
    label: Confirmation
    description: I have you selected the right Project and repo name 
    options:
      - label: I have selected the project and repo name correctly
  validations:
    required: true
