name: 💡 Requirement Request
description: Propose a new requirement
title: "💡 [REQUIREMENT] : "
labels:
  - enhancement
projects: 
  - ["YogendraBG/2"]

body:
- type: textarea
  id: description
  attributes:
    label: Requirement Description
    description: |
      Provide a detailed description of the new requirement you are proposing.
  validations:
    required: true
    
- type: textarea
  id: constraints-dependencies
  attributes:
    label: Constraints and Dependencies
    description: |
      Outline any constraints or dependencies that should be considered for this requirement.
      - 

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: |
      Add any additional context or information that might be helpful for understanding your requirement.
  validations:
    required: true

- type: input
  id: design-links
  attributes:
    label: Design links
    placeholder: please add figama link
    description: |
      Add Figma design link
      
  validations:
    required: false
    

- type: checkboxes
  id: terms
  attributes:
    label: Confirmation
    description: Is this a Feature Request?
    options:
      - label: I have Selected Project, Repo and provided necessary linnks
        required: true
