name: 💡 Requirement Request
description: Propose a new requirement
title: "💡 [REQUIREMENT] : "
labels:
  - enhancement
projects: 
  - "yogendrabg/2"

body:
- type: textarea
  id: description
  attributes:
    label: Requirement Description
    description: |
      Provide a detailed description of the new requirement you are proposing.

- type: textarea
  id: constraints-dependencies
  attributes:
    label: Constraints and Dependencies
    description: |
      Outline any constraints or dependencies that should be considered for this requirement.
      - 

- type: textarea
  id: additional-context
  attributes:
    label: Additional Context
    description: |
      Add any additional context or information that might be helpful for understanding your requirement.
  validations:
    required: true

- type: input
  id: design-links
  attributes:
    label: Design links
    placeholder: please add figama link
    description: |
      Add Figma design link
      
  validations:
    required: true
    

- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
